package main

import (
	"context"
	"log/slog"
	"os"
	"os/signal"
	"time"

	"github.com/falmar/gopilot"
	"github.com/mafredri/cdp/protocol/fetch"
)

func main() {
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, os.Kill)
	defer cancel()

	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))

	cfg := gopilot.NewBrowserConfig()
	b := gopilot.NewBrowser(cfg, logger)

	err := b.Open(ctx, &gopilot.BrowserOpenInput{})
	if err != nil {
		logger.Error("unable to open browser", "error", err)
		return
	}
	defer b.Close(ctx)

	pOut, err := b.NewPage(ctx, &gopilot.BrowserNewPageInput{})
	if err != nil {
		logger.Error("unable to open page", "error", err)
		return
	}
	page := pOut.Page
	defer page.Close(ctx)

	// Enable fetch interception
	if err := page.EnableFetch(ctx); err != nil {
		logger.Error("unable to enable fetch", "error", err)
		return
	}
	defer page.DisableFetch(ctx)

	// Add request interceptor to modify outgoing requests
	requestHandle := page.AddInterceptRequest(ctx, func(ctx context.Context, req *fetch.RequestPausedReply, continueArgs *fetch.ContinueRequestArgs) (*fetch.FulfillRequestArgs, error) {
		// Log the original request
		logger.Info("intercepted request",
			"url", req.Request.URL,
			"method", req.Request.Method,
			"headers", req.Request.Headers)

		// Check if this is a request to httpbin.org/get
		if req.Request.URL == "https://httpbin.org/get" {
			// For demonstration, let's fulfill this request with a custom response
			logger.Info("fulfilling request with custom response")

			// Create a custom JSON response
			responseBody := `{
	"custom_response": true,
	"message": "This response was generated by GoPilot!",
	"original_url": "` + req.Request.URL + `"
}`

			// Create the fulfill request arguments
			fulfillArgs := &fetch.FulfillRequestArgs{
				RequestID:    req.RequestID,
				ResponseCode: 200,
				ResponseHeaders: []fetch.HeaderEntry{
					{Name: "Content-Type", Value: "application/json"},
					{Name: "X-Fulfilled-By", Value: "GoPilot"},
				},
				Body: []byte(responseBody),
			}

			// Return the fulfill args to stop the callback chain and fulfill the request
			return fulfillArgs, nil
		}

		// For other requests, just modify headers and continue
		logger.Info("modifying request headers")

		continueArgs.Headers = append([]fetch.HeaderEntry{}, fetch.HeaderEntry{
			Name:  "X-Modified-By",
			Value: "Gopilot!",
		})

		// Return nil, nil to continue the request with modified continueArgs
		return nil, nil
	})
	defer page.RemoveInterceptRequest(ctx, requestHandle)

	// First navigate to httpbin.org/headers to demonstrate request header modification
	logger.Info("Navigating to httpbin.org/headers to demonstrate header modification")
	if _, err := page.Navigate(ctx, &gopilot.PageNavigateInput{
		URL:                "https://httpbin.org/headers",
		WaitDomContentLoad: true,
	}); err != nil {
		logger.Error("unable to navigate to /headers", "error", err)
		return
	}

	// Wait to see the results of header modification
	logger.Info("Waiting 5 seconds to see the results of header modification...")
	time.Sleep(5 * time.Second)

	// Then navigate to httpbin.org/get to demonstrate custom response fulfillment
	logger.Info("Navigating to httpbin.org/get to demonstrate custom response fulfillment")
	if _, err := page.Navigate(ctx, &gopilot.PageNavigateInput{
		URL:                "https://httpbin.org/get",
		WaitDomContentLoad: true,
	}); err != nil {
		logger.Error("unable to navigate to /get", "error", err)
		return
	}

	// Wait to see the results of custom response fulfillment
	logger.Info("Waiting 5 seconds to see the results of custom response fulfillment...")
	time.Sleep(5 * time.Second)
}
